a <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
feb <- subset(a, Date=="2/2/2007" | Date=="1/2/2007")
feb$DateTime <- as.POSIXct(strptime(paste(feb$Date, feb$Time),  "%d/%m/%Y %H:%M:%S"))
png(filename = "plot3.png")
plot(feb$DateTime, feb$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(feb$DateTime, feb$Sub_metering_2, type="l", col="red")
lines(feb$DateTime, feb$Sub_metering_3, type="l", col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red", "blue"), lty=1)
dev.off()
